name: PRs to main
on: 
  push:
    branches: [main]
jobs:
  merge-main-back-to-dev:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: set-result
      with:
        script: |
          const commits = ${{ toJSON(github.event.commits) }}
          for (const commit of commits) {
            console.log(commit.message);
          }
          const result = commits.some(commit => commit.message.includes("fix"))
          return result
        result-encoding: string
    - name: echo result
      run: |
       echo "${{steps.set-result.outputs.result}}"
    - uses: actions/checkout@v3
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge main back to dev
      run: |
        if echo ${{ steps.set-result.outputs.result }} | grep -c "true"
        then
          git fetch --unshallow
          git checkout dev
          git pull
          git merge --no-ff main -m "Auto-merge main back to dev"
          git push
        fi
